version: 0.2
           
phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - npm update -g npm
      - npm install
  build:
    commands:
      - npm run build --mode ${BUILD_MODE}
  post_build:
    commands:
      - aws s3 sync dist s3://${S3_BUCKET} --delete